[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[form]
  [form.settings]
    # Enable form notifications
    [form.settings.notification]
      # Send form submissions to this email
      email = "mail@kevinfroger.nl"